services:
    oc_antispam.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - 50
        calls:
          - [ setLocale, [%locale%]]

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
          - "@oc_antispam.antispam"
        tags:
          - { name: twig.extension }

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
            - "%email%"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purger\AdvertPurger
        arguments:
            - "@oc_platform.email.application_mailer"
            - "@doctrine.orm.entity_manager"

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }

    oc_platform.form.ckeditor:
        class: OC\PlatformBundle\Form\CkeditorType
        tags:
          - { name: form.type, alias: ckeditor }

    oc_platform.paramconverter.json:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
          - { name: request.param_converter }

    #oc_platform.beta.html_adder:
        #class: OC\PlatformBundle\Event\BetaHTMLAdder

    #oc_platform.beta.listener:
        #class: OC\PlatformBundle\Listener\BetaListener
        #arguments:
         # - "@oc_platform.beta.html_adder"
         # - "2018-03-28"
        #tags:
         # - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    #oc_platform.welcome.js_adder:
        #class: OC\PlatformBundle\Event\WelcomeEvent

    #oc_platform.welcome.listener:
        #class: OC\PlatformBundle\Listener\WelcomeListener
        #arguments:
          #- "@oc_platform.welcome.js_adder"
        #tags:
          #- { name: kernel.event_listener, event: kernel.response, method: processWelcome }